env:
  deploy:
    FIREBASE_EMAIL:
      secure: "qdss3PVfdHGMqIWho8KjQi7cLgjV8DB/VDm0EmK6u0LWrQazQyRqCz6QlU+dvTGvK31IVZXd6Y002X0a5xC2QZ9nGCizKWDki1wFR2xoAdIM4un2R37d0uZEu28cyhrGKuaat5VNPfGIxal+kTYQhAD3AlXTzOURnQo2X+DWhMEU1VqgXEr+HrXyhSiIG
      hPzPDfM8xrcrwI8Ff2YAQClkaf5Hi1gOJXC7gHBJ7UUaMcCTlXVetnKebsevl8lPqlKwcBnntdB9e1RngiRk4PKFnUUUIsbsoLHRfLAhT4UMFC24wFEbJmrLG0i9mRJcIOo5ivtDRkyQXWx3NGjNzU4AafKX3l6LIe9D7iF9skF3pY4naVsxhHAUJ5JKaH1UYC0OCX
      taKf28qDBHAZFfSwGEfBi73tRC8KDrCAELGJe9hAU6dahUhcEyz0JgMCEfASKQmT+fUUrUY+7A+p5Vgf04t92Hy3+O07a3SKLAmI6z+ZUdWyM0cca2JL25i1e/VAp9DpcDusFcLYmcpyRLogMkf0MX/yCZkPRs+jd2nq9qeq4TtflIHtybNklJzdhiUl8E2rR8QEma
      O0FP0kMVj3CMgK/RGiRHpSioLSzXMwfgwWlA/0upJZsf9wczBooZNden5jFWbeGgBbvRUZ+cJhFBC8riX6hrzsgfk1Ko="
    FIREBASE_PASSWORD:
      secure: "qdss3PVfdHGMqIWho8KjQi7cLgjV8DB/VDm0EmK6u0LWrQazQyRqCz6QlU+dvTGvK31IVZXd6Y002X0a5xC2QZ9nGCizKWDki1wFR2xoAdIM4un2R37d0uZEu28cyhrGKuaat5VNPfGIxal+kTYQhAD3AlXTzOURnQo2X+DWhMEU1VqgXEr+HrXyhSiIG
      hPzPDfM8xrcrwI8Ff2YAQClkaf5Hi1gOJXC7gHBJ7UUaMcCTlXVetnKebsevl8lPqlKwcBnntdB9e1RngiRk4PKFnUUUIsbsoLHRfLAhT4UMFC24wFEbJmrLG0i9mRJcIOo5ivtDRkyQXWx3NGjNzU4AafKX3l6LIe9D7iF9skF3pY4naVsxhHAUJ5JKaH1UYC0OCX
      taKf28qDBHAZFfSwGEfBi73tRC8KDrCAELGJe9hAU6dahUhcEyz0JgMCEfASKQmT+fUUrUY+7A+p5Vgf04t92Hy3+O07a3SKLAmI6z+ZUdWyM0cca2JL25i1e/VAp9DpcDusFcLYmcpyRLogMkf0MX/yCZkPRs+jd2nq9qeq4TtflIHtybNklJzdhiUl8E2rR8QEma
      O0FP0kMVj3CMgK/RGiRHpSioLSzXMwfgwWlA/0upJZsf9wczBooZNden5jFWbeGgBbvRUZ+cJhFBC8riX6hrzsgfk1Ko="
language: "node_js"
node_js:
  - "0.12"
  - "iojs"
before_script:
  - "npm install -g bower"
  - "bower install"
before_install:
  # replace chromium with chrome
  - "sudo apt-get remove chromium-browser"
  - "sudo apt-get update"
  - "sudo apt-get install libappindicator1"
  - "sudo apt-get install fonts-liberation"
  - "wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
  - "sudo dpkg -i google-chrome-stable_current_amd64.deb"
  - "sudo apt-get install -f"
  - "export CHROME_SANDBOX=/opt/google/chrome/chrome-sandbox"
  # Download a custom chrome-sandbox which works inside OpenVC containers (used in travis).
  - "sudo rm -f $CHROME_SANDBOX"
  - "sudo wget https://googledrive.com/host/0B5VlNZ_Rvdw6NTJoZDBSVy1ZdkE -O $CHROME_SANDBOX"
  - "sudo chown root:root $CHROME_SANDBOX; sudo chmod 4755 $CHROME_SANDBOX"
  - "sudo md5sum $CHROME_SANDBOX"
  - "export DISPLAY=:99.0"
  - "Xvfb :99.0 -extension RANDR > /dev/null &"
  - "sudo chmod 1777 /dev/shm"
after_succes:
  - npm install gulp
  - gulp
  - mkdir /home/travis/tmp
  - npm install -g firebase-tools
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then echo -e "${FIREBASE_EMAIL}\n${FIREBASE_PASSWORD}" | firebase deploy; fi
