language: "node_js"
node_js:
  - "0.12"
  - "iojs"
before_install:
  # replace chromium with chrome
  - "sudo apt-get remove chromium-browser"
  - "sudo apt-get update"
  - "sudo apt-get install libappindicator1"
  - "sudo apt-get install fonts-liberation"
  - "wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
  - "sudo dpkg -i google-chrome-stable_current_amd64.deb"
  - "sudo apt-get install -f"
  - "export CHROME_SANDBOX=/opt/google/chrome/chrome-sandbox"
  # Download a custom chrome-sandbox which works inside OpenVC containers (used in travis).
  - "sudo rm -f $CHROME_SANDBOX"
  - "sudo wget https://googledrive.com/host/0B5VlNZ_Rvdw6NTJoZDBSVy1ZdkE -O $CHROME_SANDBOX"
  - "sudo chown root:root $CHROME_SANDBOX; sudo chmod 4755 $CHROME_SANDBOX"
  - "sudo md5sum $CHROME_SANDBOX"
  - "export DISPLAY=:99.0"
  - "Xvfb :99.0 -extension RANDR > /dev/null &"
  - "sudo chmod 1777 /dev/shm"
before_script:
  - "npm install -g bower"
  - "bower install"
  - "npm install firebase-tools"
deploy:
  - "gulp deploy"
